"""Sphinx configuration for the Tethys public docs site.

Build:
    sphinx-build -W -c docs/site -b html docs docs/_build/html

The site source lives under :file:`docs/`. The entry point is
:file:`docs/site/index.md`. MyST-Parser + Furo + sphinx-design power
the look; ``sphinxcontrib-mermaid`` renders the architecture diagrams
embedded in the runbooks + ADRs.

F6 of :file:`docs/research/phase-0-empty-folders-scaffold.md` pulls the
seven Markdown pages under :file:`master/docs/` into the build at
``builder-inited`` time. We picked the **copy-to-mirror** approach
over a ``myst_parser`` include directive because:

* Sphinx's source-discovery walker only considers files under
  ``srcdir``. ``master/docs/`` is outside ``srcdir`` (``docs/``).
* A copy hook is portable across operating systems (no symlink
  privilege requirement on Windows), keeps the mirror in lockstep with
  every build, and never pollutes the repo (the mirror dir lives under
  the git-ignored ``docs/_build_master_docs_mirror/``).

The mirror is exposed in the site at ``/master-tool/<page>`` via the
"Master tool internals" toctree section in :file:`docs/site/index.md`.

Cite: parent plan §11 (public deliverables — Sphinx + GitHub Pages).
Cite: ADR-0008 (license-free toolchain — Sphinx + MyST + Furo).
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

# ---- Paths ----------------------------------------------------------------

_CONF_DIR = Path(__file__).resolve().parent  # docs/site/
_DOCS_DIR = _CONF_DIR.parent  # docs/
_REPO_ROOT = _DOCS_DIR.parent  # repo root
_MASTER_DOCS_SOURCE = _REPO_ROOT / "master" / "docs"
_MASTER_DOCS_MIRROR_NAME = "_build_master_docs_mirror"
_MASTER_DOCS_MIRROR = _DOCS_DIR / _MASTER_DOCS_MIRROR_NAME

sys.path.insert(0, str(_CONF_DIR))

# ---- Project information --------------------------------------------------

project = "Tethys"
author = "Tethys contributors"
copyright = "2026, Tethys contributors"  # noqa: A001 — Sphinx convention
release = "0.1.0-dev"

# ---- Sphinx core ----------------------------------------------------------

extensions = [
    "myst_parser",
    "sphinx_design",
    "sphinxcontrib.mermaid",
]

source_suffix = {
    ".md": "markdown",
    ".rst": "restructuredtext",
}

# Tethys uses docs/site/index.md as the canonical entry; the rest of the
# site source lives under docs/ + subdirectories.
root_doc = "site/index"

exclude_patterns = [
    "_build",
    "_build_master_docs_mirror/index.md",  # uses /master-tool/index instead
    "**/.ipynb_checkpoints",
    "**/.venv-docs/**",
    ".venv-docs/**",
    "**/.venv/**",
    "site/conf.py",
]

# ---- MyST-Parser ----------------------------------------------------------

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "linkify",
    "tasklist",
    "substitution",
]
myst_heading_anchors = 4

# ---- HTML theme -----------------------------------------------------------

html_theme = "furo"
html_title = "Tethys — XCP for extreme environments"
html_static_path: list[str] = []

# ---- master/docs mirror ---------------------------------------------------


def _mirror_master_docs(app, _config=None) -> None:
    """Copy ``master/docs/*.md`` into ``docs/_build_master_docs_mirror/``.

    Fires on ``builder-inited`` so the mirror exists before Sphinx walks
    ``srcdir``. The mirror is git-ignored.
    """
    if not _MASTER_DOCS_SOURCE.is_dir():
        return
    target_dir = _MASTER_DOCS_MIRROR
    if target_dir.exists():
        shutil.rmtree(target_dir)
    target_dir.mkdir(parents=True, exist_ok=True)
    for md_path in sorted(_MASTER_DOCS_SOURCE.glob("*.md")):
        shutil.copy2(md_path, target_dir / md_path.name)
    # Mark the mirror with a stamp file so reviewers know it's auto-generated.
    (target_dir / ".sphinx-mirror.stamp").write_text(
        f"Generated by docs/site/conf.py from {_MASTER_DOCS_SOURCE.relative_to(_REPO_ROOT)}.\n"
        "Do not edit by hand; edit the source files under master/docs/ instead.\n",
        encoding="utf-8",
    )


def setup(app):  # noqa: D401 — Sphinx convention
    """Register the mirror hook."""
    app.connect("builder-inited", _mirror_master_docs)
    return {
        "version": release,
        "parallel_read_safe": True,
        "parallel_write_safe": True,
    }


# ---- Safety / build hardening --------------------------------------------

# Treat suppressible warnings as warnings; never as silent passes.
suppress_warnings: list[str] = []

# Cache directory under .venv-docs / build dir to avoid polluting srcdir.
needs_sphinx = "7.0"

# Used by readthedocs-style cross-references; the project does not yet
# ship intersphinx mapping (Phase 11 PR adds it).
intersphinx_mapping: dict[str, tuple[str, None]] = {}

# Ensure deterministic output on CI even with PYTHONHASHSEED unset.
os.environ.setdefault("PYTHONHASHSEED", "0")
