/*
 * tethys/tethys_export.h - test-build stub.
 *
 * The production tethys_export.h is generated by CMake's GenerateExportHeader
 * (see slave/CMakeLists.txt). When Ceedling builds the test binary it does
 * not invoke CMake, so this stub provides empty visibility macros so the
 * production headers compile cleanly under the test toolchain.
 *
 * Trace: docs/research/phase-1-shared-infrastructure-execution.md
 */
#ifndef TETHYS_TETHYS_EXPORT_H
#define TETHYS_TETHYS_EXPORT_H

#define TETHYS_EXPORT
#define TETHYS_NO_EXPORT
#define TETHYS_DEPRECATED
#define TETHYS_DEPRECATED_EXPORT
#define TETHYS_DEPRECATED_NO_EXPORT

#define TETHYS_STATIC_DEFINE

#endif /* TETHYS_TETHYS_EXPORT_H */
