#!/usr/bin/env python3
"""Convert a .cursor/rules/*.mdc file to .github/instructions/*.instructions.md.

Frontmatter translation:
    globs: <pattern>          -> applyTo: '<pattern>'
    alwaysApply: true         -> applyTo: '**'

Body is copied verbatim under a "Mirror of" header pointing at the source.

Usage:
    python3 _convert.py <source.mdc> <dest.instructions.md>

This is the script half of PR-7 follow-up F1; PR-4 ships it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    """Return (frontmatter dict, body) for a YAML-frontmatter markdown file."""
    if not text.startswith("---"):
        return {}, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return {}, text
    front_block = parts[1].strip()
    body = parts[2].lstrip("\n")
    front: dict[str, str] = {}
    for line in front_block.splitlines():
        if ":" in line:
            key, _, value = line.partition(":")
            front[key.strip()] = value.strip()
    return front, body


def build_apply_to(front: dict[str, str]) -> str:
    """Translate Cursor frontmatter to Copilot applyTo string."""
    always = front.get("alwaysApply", "false").lower() == "true"
    globs = front.get("globs", "").strip()
    if always or not globs:
        return "**"
    return globs


def convert(src: Path, dest: Path) -> None:
    raw = src.read_text(encoding="utf-8")
    front, body = parse_frontmatter(raw)
    description = front.get("description", "").strip().strip("'\"")
    apply_to = build_apply_to(front)
    name = src.stem
    new_front = (
        "---\n"
        f"description: {description}\n"
        f"applyTo: '{apply_to}'\n"
        "---\n\n"
        f"> Mirror of [`.cursor/rules/{name}.mdc`](../../.cursor/rules/{name}.mdc). "
        "Source of truth lives there; this file is regenerated by "
        "`infrastructure/rules/sync.sh` (bash) or `sync.ps1` (PowerShell). "
        "GitHub Copilot Workspace consumes this directory.\n\n"
    )
    combined = new_front + body.rstrip() + "\n"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(combined, encoding="utf-8", newline="\n")


def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <source.mdc> <dest.instructions.md>", file=sys.stderr)
        return 2
    convert(Path(sys.argv[1]), Path(sys.argv[2]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
